version: '3.8'  # Usa una versiÃ³n compatible

services:
  mongodb:  # Nombre del servicio
    image: mongo:latest  # Usa una versiÃ³n especÃ­fica como "mongo:4.2.1" para mayor estabilidad:cite[6]:cite[8]
    container_name: mi_mongodb
    restart: always  # Para que se reinicie automÃ¡ticamente si falla
    ports:
      - "27017:27017"  # MAPEO DE PUERTOS: puerto_de_tu_equipo:puerto_del_contenedor
    environment:
      MONGO_INITDB_ROOT_USERNAME: usuario  # ğŸ” NOMBRE DE USUARIO para el administrador
      MONGO_INITDB_ROOT_PASSWORD: 1234     # ğŸ” CONTRASEÃ‘A para el administrador
    volumes:
      - ../mongo_data:/data/db  # ğŸ’¾ Persistencia de datos (opcional, pero recomendado)